import {
  File,
  Image,
  Film
} from 'lucide-react';


export default [
  {
    id: "m5gr84i1",
    icon: Image,
    name: "App inspiration.png",
    modified: "about a min ago",
    modifiedBy: "Ralph Edwards",
    fileSize: "200 KB",
    sharing: "Private",
    activity: "Olivia Rhye",
  },
  {
    id: "m5gr84i2",
    icon: File,
    name: "Tech requirements.pdf",
    modified: "Jan 4, 2022",
    modifiedBy: "Eleanor Pena",
    fileSize: "720 KB",
    sharing: "Private",
    activity: "Phoenix Baker",
  },
  {
    id: "m5gr84i3",
    icon: Image,
    name: "Dashboard screenshot.jpg",
    modified: "Jan 2, 2022",
    modifiedBy: "Cody Fisher",
    fileSize: "16 MB",
    sharing: "Private",
    activity: "Lana Steiner",
  },
  {
    id: "m5gr84i4",
    icon: Film,
    name: "Dashboard prototype recording.mp4",
    modified: "about a min ago",
    modifiedBy: "Bessie Cooper",
    fileSize: "4.2 MB",
    sharing: "Private",
    activity: "Demi Wilkinson",
  },
  {
    id: "m5gr84i5",
    icon: File,
    name: "Dashboard prototype FINAL.fig",
    modified: "Jan 8, 2022",
    modifiedBy: "Leslie Alexander",
    fileSize: "400 KB",
    sharing: "Private",
    activity: "Candice Wu",
  },
  {
    id: "m5gr84i6",
    icon: File,
    name: "UX Design Guidelines.docx",
    modified: "Jan 6, 2022",
    modifiedBy: "Jane Cooper",
    fileSize: "12 MB",
    sharing: "Private",
    activity: "Natali Craig",
  },
  {
    id: "m5gr84i7",
    icon: File,
    name: "Dashboard interaction.framerx",
    modified: "Jan 4, 2022",
    modifiedBy: "Savannah Nguyen",
    fileSize: "800 KB",
    sharing: "Private",
    activity: "Drew Cano",
  },
];